# Generated by Django 2.0 on 2018-10-27 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='ip')),
                ('flag', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='说明')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user_id', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.User', to_field='user_id')),
            ],
            options={
                'db_table': 't_user_log',
            },
        ),
    ]
