# Generated by Django 2.1.3 on 2019-02-17 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.TextField(max_length=10000, verbose_name='说明')),
                ('remark', models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('case_id', models.ForeignKey(db_column='case_id', on_delete=django.db.models.deletion.CASCADE, to='app.TestCase', to_field='case_id')),
                ('user_id', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.User', to_field='user_id')),
            ],
            options={
                'db_table': 't_testcase_history',
            },
        ),
        migrations.AddField(
            model_name='testcasereview',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
