# Generated by Django 2.0 on 2018-10-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity',
            field=models.IntegerField(choices=[('0', '超级管理员'), ('1', '普通用户')], default=1, verbose_name='用户身份'),
            preserve_default=False,
        ),
    ]
