# Generated by Django 2.1.3 on 2019-02-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190217_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='desc',
            field=models.CharField(default=None, max_length=500, verbose_name='介绍说明'),
        ),
        migrations.AddField(
            model_name='pages',
            name='desc',
            field=models.CharField(default=None, max_length=500, verbose_name='介绍说明'),
        ),
    ]
