# Generated by Django 2.1.3 on 2019-02-26 13:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190217_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='bughistory',
            name='record_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
