# Generated by Django 2.1.3 on 2019-02-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bughistory_record_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bughistory',
            name='remark_status',
            field=models.IntegerField(choices=[('0', '删除'), ('1', '新建'), ('2', '修改')], default=1, verbose_name='备注状态'),
        ),
    ]
