# Generated by Django 2.1.3 on 2019-02-26 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_bughistory_remark_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcasefiles',
            old_name='file_path',
            new_name='url',
        ),
    ]
